### ISSUE TITLE
Nano RP2040 Connect firmware update

### ISSUE THREAD

**Issue by LEBsci** [arduino-libraries/WiFiNINA#194]
I'm following [this](https://www.arduino.cc/en/Tutorial/WiFiNINAFirmwareUpdater) guide trying to update the firmware on the board and I get this message after running the CheckFirmwareVersion example:
```
WiFiNINA firmware check.

Firmware version installed: 1.3.0
Latest firmware version available : 1.4.7

Check result: NOT PASSED
 - The firmware version on the module does not match the
   version required by the library, you may experience
   issues or failures.
```

I'm using Arduino IDE 1.8.13 and the WiFiNINA library is on the 1.8.12 version. I've used the "FirmwareUpdater" sketch with no response at all from the serial monitor and also the  Firmware Uploader plug-in in which the most recent firmware version I find is 1.3.0. I've been having issues trying the simple examples on the board and I think the firmware version might be the reason.

**Comment by per1234** [comment]
Hi @LEBsci. The Arduino IDE comes with the latest version of the NINA firmware at the time of its release. When Arduino IDE 1.8.13  was released a year ago, the latest firmware version was 1.3.0. The latest Arduino IDE 1.8.15 release contains firmware versions up to 1.4.5, but that still won't get you the latest NINA firmware 1.4.7.

The easiest way to get the latest firmware installed is to upload an[ Arduino IoT Cloud](https://docs.arduino.cc/cloud/iot-cloud/tutorials/iot-cloud-getting-started) Thing sketch to your board via the IoT Cloud integrated sketch editor, not via the "full editor" (Arduino Web Editor). This will automatically check the firmware version on your board and update it if it's not the latest.

If you don't want to use Arduino IoT Cloud, then the alternative to get the latest NINA firmware version is the Arduino Firmware Uploader command line tool:
https://arduino.github.io/arduino-fwuploader/1.0/
Since this issue tracker is intended for reporting bugs or making feature requests, and not for support discussions, if you would like assistance with updating the firmware via either of those methods, please post on the Arduino Forum. I'll be happy to help you out over there:
https://forum.arduino.cc/
