### ISSUE TITLE
Version 1.8.14 doesn't work with Scheduler again

### ISSUE THREAD

**Issue by skillsfactory** [arduino-libraries/WiFiNINA#258]
Scheduler version is 0.4.4 on Arduino Nano IoT 33

**Comment by pennam** [comment]
Hi @skillsfactory,
if you have issues with the cloud scheduler please open a thread on the forum https://forum.arduino.cc/c/software/iot-cloud/152 or an issue on the https://github.com/arduino-libraries/ArduinoIoTCloud library.
 
 I'm closing this because it is unlikely that the issues comes from WiFiNINA library.
