### ISSUE TITLE
MKR WiFi 1010 not connecting to wifi

### ISSUE THREAD

**Issue by 01ste02** [arduino-libraries/WiFiNINA#69]
Yesterday, my code worked nicely at first, but without any code changes it stopped working after I soldered the arduino to a protoboard. I took care not to put the soldering iron on it for more than a second, and used a really low-temperature solder with a really low temperature setting on my soldering iron. After soldering, I can still communicate with the WiFi chip, as the example sketches for scanning networks don't complain that they can't find the module. I can fetch the firmware version for it as well.

But any task that involves the antenna seem to fail. ScanNetworks gives me 0 available networks, and my program gets stuck on trying to connect. Could I have overheated the antenna or am I using any pins that should be reserved for the WiFi chip? I am using pins 0 to 11 and the 5v, vcc and ground.

[Schematic, using an arduino uno as my program for creating schematics doesn't have the MKR WiFi 1010 yet](https://drive.google.com/open?id=1PaB3QAO6_WRkP93rWJSV1Z3hZbQif7jh)

EDIT: I tried upgrading the firmware version to the latest (1.2.1) in case I had ran into some bug with voltage instabilities or something (unlikely, I know... But at least I tried to fix it :)). The upgrade completed without any issues and the CheckFirmwareVersion example shows the correct firmware version.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

I see you have already created a forum thread, and I have answered there:
https://forum.arduino.cc/index.php?topic=624782
If we do discover your problem is caused by a bug in Arduino's software, I'll be sure to reopen this issue.
