### ISSUE TITLE
WiFi.getTime() not in documentation

### ISSUE THREAD

**Issue by ocrdu** [arduino-libraries/WiFiNINA#85]
Hi,

WiFi.getTime() is implemented in this library and works fine, but is not documented on https://www.arduino.cc/en/Reference/WiFiNINA.

**Comment by thekunalsaini** [comment]
would you like to add documentation of WIFI.getTime()

**Comment by rjs5327** [comment]
rtc.begin();

  unsigned long epoch;
  int numberOfTries = 0, maxTries = 6;
  do { epoch = WiFi.getTime();   numberOfTries++;  if(epoch == 0){delay(2000);} }
  while ((epoch == 0) && (numberOfTries < maxTries));

  if (numberOfTries >= maxTries) {  Serial.print("NTP unreachable!!");  }
  else {
    Serial.print("Epoch received: ");
    Serial.println(epoch);
    rtc.setEpoch(epoch+(GMT*3600));
    Serial.println();
  }

**Comment by rjs5327** [comment]
This is tested and proven on MKR 1010

**Comment by rjs5327** [comment]
per1234,

What is the bug?  I am running this code on a MKR1010 right now with no issues.  It just needs added to the documentation and i dont have access.

**Comment by rjs5327** [comment]
[GetTime.zip](https://github.com/arduino-libraries/WiFiNINA/files/4494503/GetTime.zip)

**Comment by per1234** [comment]
>What is the bug?

@rjs5327 the bug is that part of the public API of this library is undocumented. It's a defect in the documentation, thus the bug label.

>It just needs added to the documentation and i dont have access.

Yes, this library's documentation is not hosted in a public repository so only someone with edit access to Arduino's documentation is able to fix this. Since none of us are able to do anything about this issue, I suggest we refrain from any further discussion here, since it serves no constructive purpose. Commenting unnecessarily on issues spams the people watching the repository.

**Comment by imranmoezkhan** [comment]
Apparently this is now documented:
https://www.arduino.cc/en/Reference/WiFiNINAGetTime
But isn't mentioned anywhere in wifi NINA's reference page:
https://www.arduino.cc/en/Reference/WiFiNINA

Is the reference page a hanging link?

**Comment by karlsoderby** [comment]
This issue is now fixed. Thank you everyone for reporting it.
